spring:
  application:
    name: app-api-price

  profiles:
    active: local

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId}] %msg%n"

app:
  popular:
    count:
      windows: M15,H1,D1,D7
  ticker:
    extract:
      path-variable-names: [ ticker, symbol ]
      query-param-names: [ ticker, symbol ]
      header-names: [ X-Ticker ]
