spring:
  config:
    activate:
      on-profile: local

  application:
    name: app-api-price

  data:
    redis:
      host: localhost
      port: 6379

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId}] %msg%n"

  level:
    com.polynomeer.infra.redis: DEBUG
    com.polynomeer.infra.timescaledb: DEBUG
    com.polynomeer.domain.price: DEBUG
