spring:
  config:
    activate:
      on-profile: local

  application:
    name: app-batch-collector

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/romanticker
    username: romanticker
    password: romanticker
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId}] %msg%n"
  level:
    com.polynomeer.app.batch: DEBUG
    com.polynomeer.infra.redis: DEBUG
    com.polynomeer.infra.timescaledb: DEBUG
    com.polynomeer.infra.external: DEBUG
